### ISSUE TITLE
Empty API response causes exception

### ISSUE THREAD

**Issue by four43** [aerisweather/python-tools#4]
When playing with historical_conditions_date_range_download.ipynb I received the following error while running it:

![image](https://user-images.githubusercontent.com/517006/193585483-4b117c16-105e-42b3-bb01-e07e3e34f4b2.png)

Lets have it check the http code, then the `success` part of the response and output a nicer error message. The error is good that it passed it along, but having a nicer message would be more helpful to the user.

**Comment by bclark28** [comment]
fixed with 9779c8fbca528d233570112aaad463097471b2d7
